spring:
  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.0.10.122
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 1q2w3e!Q@W#E
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 空闲对象逐出器线程的运行间隔时间
        time-between-eviction-runs: 10s
    # 连接超时时间（毫秒）
    timeout: 1200
  # Redission配置
  redisson:
    nodes:
      - host: 10.0.10.122
        port: 6379
        password: 1q2w3e!Q@W#E
