server:
  port: 8080

spring:
  application:
    name: monitor-prometheus-demo

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
