spring:
  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.0.10.123
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 1q2w3e!Q@W#E
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 空闲对象逐出器线程的运行间隔时间
        time-between-eviction-runs: 10s
    # 连接超时时间（毫秒）
    timeout: 1200

mybatis-plus:
  # 扫描Mapper接口对应的XML文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 命名自动驼峰转换
    map-underscore-to-camel-case: true
    #  global-config:
    #    db-config:
    # 主键类型，auto：数据库id自增
#      id-type: assign_id